import { useEffect, useState } from 'react';
import { AccountList, AuditList, SystemStatus, Card, Button, TextField, PasswordChangeForm, MfaEnrollmentPanel, RecoveryCodesPanel, SessionList, type AccountProjection, type AuditEventProjection, type HealthProjection, type SystemInfoProjection, type AuthSessionSummary } from '@datarelay-labs/foundation';
import { api } from './api';
import { authAdapter, accountsAdapter, operationsAdapter } from './foundation.config';
import { Form, Select, useTask } from './common';
import type { User } from './types';

export function Administration() {
 const [accounts,setAccounts]=useState<readonly AccountProjection[]>([]);const [events,setEvents]=useState<readonly AuditEventProjection[]>([]);const [health,setHealth]=useState<HealthProjection>();const [info,setInfo]=useState<SystemInfoProjection>();const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState('member');const task=useTask();
 async function load(){const [a,e,h,i]=await Promise.all([accountsAdapter.list(),operationsAdapter.listAudit!(),operationsAdapter.readHealth(),operationsAdapter.readSystemInfo()]);setAccounts(a);setEvents(e);setHealth(h);setInfo(i);}
 useEffect(()=>{void task.run(load);},[]);
 return <div className="grant-stack">{task.feedback}<div className="grant-actions"><Button variant="secondary" disabled={task.busy} onClick={()=>void task.run(load)}>Refresh administration</Button><Button variant="secondary" disabled={task.busy} onClick={()=>void task.run(async()=>{await api('/admin/mail-test','POST');task.setNotice('SMTP accepted the test message for your account. Verify actual receipt separately.');})}>Send test email to me</Button></div><SystemStatus health={health} info={info}/><Card title="Accounts"><AccountList accounts={accounts}/></Card><Card title="Create local account" description="Only Grant administrators may create users. No default or shared credentials are supplied."><Form busy={task.busy} label="Create account" onSubmit={()=>void task.run(async()=>{await api('/admin/users','POST',{username:name,email,password,role});setName('');setEmail('');setPassword('');await load();task.setNotice('Account created. Share credentials through an approved secure channel.');})}><TextField label="New username" required pattern="[a-zA-Z0-9_.@-]+" value={name} onChange={e=>setName(e.target.value)}/><TextField label="New user email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><TextField label="Initial password" type="password" autoComplete="new-password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/><Select label="New account role" value={role} onChange={setRole}><option value="member">Member</option><option value="admin">Administrator</option></Select></Form></Card><Card title="Audit history"><AuditList events={events}/></Card><Card title="Lifecycle and service configuration"><p>Backup, restore, installation origin, TLS and upgrades follow the documented operator procedures. Unsupported mutations are not exposed as working controls.</p></Card></div>;
}
export function Security({user,onSignedOut,onRefresh}:{user:User;onSignedOut:()=>void;onRefresh:()=>Promise<void>}){
 const [sessions,setSessions]=useState<readonly AuthSessionSummary[]>([]);const [material,setMaterial]=useState<{secret:string;otpauth_uri:string}|null>(null);const [codes,setCodes]=useState<string[]>([]);const task=useTask();
 async function load(){setSessions(await authAdapter.listSessions!());}
 useEffect(()=>{void task.run(load);},[]);
 return <div className="grant-stack">{task.feedback}<Card title="Change password"><PasswordChangeForm busy={task.busy} onSubmit={input=>task.run(async()=>{await authAdapter.changePassword!(input);onSignedOut();})}/></Card><Card title="Multi-factor authentication" description={user.mfa_enabled?'TOTP is enabled for your account.':'Add a second factor before using Grant for sensitive approvals.'}>{!user.mfa_enabled&&!material&&<Button disabled={task.busy} onClick={()=>void task.run(async()=>setMaterial(await api('/auth/mfa/enroll','POST')))}>Set up MFA</Button>}{material&&<MfaEnrollmentPanel material={{accountLabel:user.username,issuer:'DataRelay Grant',secret:material.secret,otpauthUri:material.otpauth_uri}} busy={task.busy} onConfirm={code=>task.run(async()=>{const r=await api<{recovery_codes:string[]}>('/auth/mfa/confirm','POST',{code});setCodes(r.recovery_codes);setMaterial(null);await onRefresh();})}/>} {!!codes.length&&<RecoveryCodesPanel codes={codes} onContinue={()=>setCodes([])}/>}</Card><Card title="Active sessions"><SessionList sessions={sessions} onRevoke={id=>task.run(async()=>{await authAdapter.revokeSession!(id);if(sessions.find(s=>s.id===id)?.current)onSignedOut();else await load();})}/></Card></div>;
}
